# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booleanQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('string_question', models.TextField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('incorrect_answers', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='multipleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('string_question', models.TextField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('incorrect_answersA', models.CharField(max_length=200)),
                ('incorrect_answersB', models.CharField(max_length=200)),
                ('incorrect_answersC', models.CharField(max_length=200)),
            ],
        ),
    ]
