# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20170616_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='scores',
            new_name='score',
        ),
    ]
