# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('string_question', models.TextField()),
                ('string_answer', models.CharField(max_length=200)),
                ('problem_image_url', models.URLField()),
                ('solution_image_url', models.URLField()),
            ],
        ),
    ]
