# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20170622_1856'),
        ('SubmitQuestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitbooleanquestion',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
        migrations.AddField(
            model_name='submitmultiplequestion',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
